refactor:pipeline mod

diff --git a/.github/workflows/relativity_main.yml b/.github/workflows/relativity_main.yml
--- a/.github/workflows/relativity_main.yml
+++ b/.github/workflows/relativity_main.yml
@@ -51,16 +51,27 @@ jobs:
       - name: Get spark-base version
         id: get-spark-base-version
         run: |
+
           # Read the file and trim whitespace/newlines
           SPARK_BASE_VERSION=$(cat spark-base-version | xargs)
+          
+          # Check if version is empty
+          if [ -z "$SPARK_BASE_VERSION" ]; then
+            echo "ERROR: spark-base-version file is empty!"
+            echo "File contents:"
+            cat spark-base-version
+            exit 1
+          fi
+          
           # Ensure version starts with 'v'
           if [[ "$SPARK_BASE_VERSION" == v* ]]; then
             SPARK_BASE_VERSION="$SPARK_BASE_VERSION"
           else
             SPARK_BASE_VERSION="v$SPARK_BASE_VERSION"
           fi
-          echo "Read spark-base version: ${SPARK_BASE_VERSION}"
-          echo "SPARK_BASE_VERSION=${SPARK_BASE_VERSION}" >> "$GITHUB_OUTPUT"
+          SPARK_IMAGE=${{secrets.BASE_IMAGE}}:${SPARK_BASE_VERSION}
+          echo "Read spark-base version: ${SPARK_IMAGE}"
+          echo "SPARK_IMAGE=${SPARK_IMAGE}" >> "$GITHUB_OUTPUT"
 
       - name: Build image
         uses: docker/build-push-action@v2
@@ -68,7 +79,7 @@ jobs:
           tags: spark-operator:local
           outputs: 'type=docker,dest=/tmp/base-image.tar'
           build-args: |
-            SPARK_IMAGE=${{ secrets.BASE_IMAGE }}:${{ steps.get-spark-base-version.outputs.SPARK_BASE_VERSION }}
+            SPARK_IMAGE=${{ steps.get-spark-base-version.outputs.SPARK_IMAGE }}
 
       - name: Cache image
         uses: actions/upload-artifact@v4
